[33mcommit 0bec982ab91005fb943aa1b34370a6f8237afe7f[m[33m ([m[1;36mHEAD -> [m[1;32mmaster[m[33m)[m
Author: unknown <estilin>
Date:   Fri Sep 29 23:34:29 2023 -0500

    cargados nuevos

.gitignore
Assets/Audios.meta
Assets/Audios/snd_blowup.ogg
Assets/Audios/snd_blowup.ogg.meta
Assets/Audios/snd_bomb.ogg
Assets/Audios/snd_bomb.ogg.meta
Assets/Audios/snd_boss_fire.ogg
Assets/Audios/snd_boss_fire.ogg.meta
Assets/Audios/snd_boss_laser.ogg
Assets/Audios/snd_boss_laser.ogg.meta
Assets/Audios/snd_boss_music.ogg
Assets/Audios/snd_boss_music.ogg.meta
Assets/Audios/snd_bossintro.ogg
Assets/Audios/snd_bossintro.ogg.meta
Assets/Audios/snd_click.ogg
Assets/Audios/snd_click.ogg.meta
Assets/Audios/snd_danger.ogg
Assets/Audios/snd_danger.ogg.meta
Assets/Audios/snd_end_drums.ogg
Assets/Audios/snd_end_drums.ogg.meta
Assets/Audios/snd_explosion_air.ogg
Assets/Audios/snd_explosion_air.ogg.meta
Assets/Audios/snd_explosion_earth.ogg
Assets/Audios/snd_explosion_earth.ogg.meta
Assets/Audios/snd_explosion_ground.ogg
Assets/Audios/snd_explosion_ground.ogg.meta
Assets/Audios/snd_explosion_solid.ogg
Assets/Audios/snd_explosion_solid.ogg.meta
Assets/Audios/snd_hurt.ogg
Assets/Audios/snd_hurt.ogg.meta
Assets/Audios/snd_jump.ogg
Assets/Audios/snd_jump.ogg.meta
Assets/Audios/snd_jump_hump.ogg
Assets/Audios/snd_jump_hump.ogg.meta
Assets/Audios/snd_landfppt.ogg
Assets/Audios/snd_landfppt.ogg.meta
Assets/Audios/snd_landing.ogg
Assets/Audios/snd_landing.ogg.meta
Assets/Audios/snd_main_theme.ogg
Assets/Audios/snd_main_theme.ogg.meta
Assets/Audios/snd_missil.ogg
Assets/Audios/snd_missil.ogg.meta
Assets/Audios/snd_reload_clip.ogg
Assets/Audios/snd_reload_clip.ogg.meta
Assets/Audios/snd_rifle_shot.ogg
Assets/Audios/snd_rifle_shot.ogg.meta
Assets/Audios/snd_select.ogg
Assets/Audios/snd_select.ogg.meta
Assets/Audios/snd_small_rifle.ogg
Assets/Audios/snd_small_rifle.ogg.meta
Assets/Audios/snd_snap.ogg
Assets/Audios/snd_snap.ogg.meta
Assets/Audios/snd_step1.ogg
Assets/Audios/snd_step1.ogg.meta
Assets/Audios/snd_step2.ogg
Assets/Audios/snd_step2.ogg.meta
Assets/Palettes.meta
Assets/Palettes/01 Palete.prefab
Assets/Palettes/01 Palete.prefab.meta
Assets/Palettes/tiles_spritesheet_0.asset
Assets/Palettes/tiles_spritesheet_0.asset.meta
Assets/Palettes/tiles_spritesheet_1.asset
Assets/Palettes/tiles_spritesheet_1.asset.meta
Assets/Palettes/tiles_spritesheet_10.asset
Assets/Palettes/tiles_spritesheet_10.asset.meta
Assets/Palettes/tiles_spritesheet_11.asset
Assets/Palettes/tiles_spritesheet_11.asset.meta
Assets/Palettes/tiles_spritesheet_12.asset
Assets/Palettes/tiles_spritesheet_12.asset.meta
Assets/Palettes/tiles_spritesheet_13.asset
Assets/Palettes/tiles_spritesheet_13.asset.meta
Assets/Palettes/tiles_spritesheet_14.asset
Assets/Palettes/tiles_spritesheet_14.asset.meta
Assets/Palettes/tiles_spritesheet_15.asset
Assets/Palettes/tiles_spritesheet_15.asset.meta
Assets/Palettes/tiles_spritesheet_16.asset
Assets/Palettes/tiles_spritesheet_16.asset.meta
Assets/Palettes/tiles_spritesheet_17.asset
Assets/Palettes/tiles_spritesheet_17.asset.meta
Assets/Palettes/tiles_spritesheet_18.asset
Assets/Palettes/tiles_spritesheet_18.asset.meta
Assets/Palettes/tiles_spritesheet_19.asset
Assets/Palettes/tiles_spritesheet_19.asset.meta
Assets/Palettes/tiles_spritesheet_2.asset
Assets/Palettes/tiles_spritesheet_2.asset.meta
Assets/Palettes/tiles_spritesheet_20.asset
Assets/Palettes/tiles_spritesheet_20.asset.meta
Assets/Palettes/tiles_spritesheet_21.asset
Assets/Palettes/tiles_spritesheet_21.asset.meta
Assets/Palettes/tiles_spritesheet_22.asset
Assets/Palettes/tiles_spritesheet_22.asset.meta
Assets/Palettes/tiles_spritesheet_23.asset
Assets/Palettes/tiles_spritesheet_23.asset.meta
Assets/Palettes/tiles_spritesheet_24.asset
Assets/Palettes/tiles_spritesheet_24.asset.meta
Assets/Palettes/tiles_spritesheet_25.asset
Assets/Palettes/tiles_spritesheet_25.asset.meta
Assets/Palettes/tiles_spritesheet_26.asset
Assets/Palettes/tiles_spritesheet_26.asset.meta
Assets/Palettes/tiles_spritesheet_27.asset
Assets/Palettes/tiles_spritesheet_27.asset.meta
Assets/Palettes/tiles_spritesheet_28.asset
Assets/Palettes/tiles_spritesheet_28.asset.meta
Assets/Palettes/tiles_spritesheet_29.asset
Assets/Palettes/tiles_spritesheet_29.asset.meta
Assets/Palettes/tiles_spritesheet_3.asset
Assets/Palettes/tiles_spritesheet_3.asset.meta
Assets/Palettes/tiles_spritesheet_30.asset
Assets/Palettes/tiles_spritesheet_30.asset.meta
Assets/Palettes/tiles_spritesheet_31.asset
Assets/Palettes/tiles_spritesheet_31.asset.meta
Assets/Palettes/tiles_spritesheet_32.asset
Assets/Palettes/tiles_spritesheet_32.asset.meta
Assets/Palettes/tiles_spritesheet_33.asset
Assets/Palettes/tiles_spritesheet_33.asset.meta
Assets/Palettes/tiles_spritesheet_34.asset
Assets/Palettes/tiles_spritesheet_34.asset.meta
Assets/Palettes/tiles_spritesheet_35.asset
Assets/Palettes/tiles_spritesheet_35.asset.meta
Assets/Palettes/tiles_spritesheet_36.asset
Assets/Palettes/tiles_spritesheet_36.asset.meta
Assets/Palettes/tiles_spritesheet_37.asset
Assets/Palettes/tiles_spritesheet_37.asset.meta
Assets/Palettes/tiles_spritesheet_38.asset
Assets/Palettes/tiles_spritesheet_38.asset.meta
Assets/Palettes/tiles_spritesheet_39.asset
Assets/Palettes/tiles_spritesheet_39.asset.meta
Assets/Palettes/tiles_spritesheet_4.asset
Assets/Palettes/tiles_spritesheet_4.asset.meta
Assets/Palettes/tiles_spritesheet_40.asset
Assets/Palettes/tiles_spritesheet_40.asset.meta
Assets/Palettes/tiles_spritesheet_41.asset
Assets/Palettes/tiles_spritesheet_41.asset.meta
Assets/Palettes/tiles_spritesheet_42.asset
Assets/Palettes/tiles_spritesheet_42.asset.meta
Assets/Palettes/tiles_spritesheet_43.asset
Assets/Palettes/tiles_spritesheet_43.asset.meta
Assets/Palettes/tiles_spritesheet_44.asset
Assets/Palettes/tiles_spritesheet_44.asset.meta
Assets/Palettes/tiles_spritesheet_45.asset
Assets/Palettes/tiles_spritesheet_45.asset.meta
Assets/Palettes/tiles_spritesheet_46.asset
Assets/Palettes/tiles_spritesheet_46.asset.meta
Assets/Palettes/tiles_spritesheet_47.asset
Assets/Palettes/tiles_spritesheet_47.asset.meta
Assets/Palettes/tiles_spritesheet_48.asset
Assets/Palettes/tiles_spritesheet_48.asset.meta
Assets/Palettes/tiles_spritesheet_49.asset
Assets/Palettes/tiles_spritesheet_49.asset.meta
Assets/Palettes/tiles_spritesheet_5.asset
Assets/Palettes/tiles_spritesheet_5.asset.meta
Assets/Palettes/tiles_spritesheet_50.asset
Assets/Palettes/tiles_spritesheet_50.asset.meta
Assets/Palettes/tiles_spritesheet_51.asset
Assets/Palettes/tiles_spritesheet_51.asset.meta
Assets/Palettes/tiles_spritesheet_52.asset
Assets/Palettes/tiles_spritesheet_52.asset.meta
Assets/Palettes/tiles_spritesheet_53.asset
Assets/Palettes/tiles_spritesheet_53.asset.meta
Assets/Palettes/tiles_spritesheet_54.asset
Assets/Palettes/tiles_spritesheet_54.asset.meta
Assets/Palettes/tiles_spritesheet_55.asset
Assets/Palettes/tiles_spritesheet_55.asset.meta
Assets/Palettes/tiles_spritesheet_56.asset
Assets/Palettes/tiles_spritesheet_56.asset.meta
Assets/Palettes/tiles_spritesheet_57.asset
Assets/Palettes/tiles_spritesheet_57.asset.meta
Assets/Palettes/tiles_spritesheet_58.asset
Assets/Palettes/tiles_spritesheet_58.asset.meta
Assets/Palettes/tiles_spritesheet_59.asset
Assets/Palettes/tiles_spritesheet_59.asset.meta
Assets/Palettes/tiles_spritesheet_6.asset
Assets/Palettes/tiles_spritesheet_6.asset.meta
Assets/Palettes/tiles_spritesheet_60.asset
Assets/Palettes/tiles_spritesheet_60.asset.meta
Assets/Palettes/tiles_spritesheet_61.asset
Assets/Palettes/tiles_spritesheet_61.asset.meta
Assets/Palettes/tiles_spritesheet_62.asset
Assets/Palettes/tiles_spritesheet_62.asset.meta
Assets/Palettes/tiles_spritesheet_63.asset
Assets/Palettes/tiles_spritesheet_63.asset.meta
Assets/Palettes/tiles_spritesheet_64.asset
Assets/Palettes/tiles_spritesheet_64.asset.meta
Assets/Palettes/tiles_spritesheet_7.asset
Assets/Palettes/tiles_spritesheet_7.asset.meta
Assets/Palettes/tiles_spritesheet_8.asset
Assets/Palettes/tiles_spritesheet_8.asset.meta
Assets/Palettes/tiles_spritesheet_9.asset
Assets/Palettes/tiles_spritesheet_9.asset.meta
Assets/Scenes.meta
Assets/Scenes/SampleScene.unity
Assets/Scenes/SampleScene.unity.meta
Assets/Scripts.meta
Assets/Scripts/JohnMovement.cs
Assets/Scripts/JohnMovement.cs.meta
Assets/Sprites.meta
Assets/Sprites/background.meta
Assets/Sprites/background/background_cave.png
Assets/Sprites/background/background_cave.png.meta
Assets/Sprites/background/background_color.png
Assets/Sprites/background/background_color.png.meta
Assets/Sprites/background/clouds1.png
Assets/Sprites/background/clouds1.png.meta
Assets/Sprites/background/clouds2.png
Assets/Sprites/background/clouds2.png.meta
Assets/Sprites/background/jungle_bg_trees.png
Assets/Sprites/background/jungle_bg_trees.png.meta
Assets/Sprites/background/jungle_paralax_bg1.png
Assets/Sprites/background/jungle_paralax_bg1.png.meta
Assets/Sprites/background/jungle_paralax_bg2.png
Assets/Sprites/background/jungle_paralax_bg2.png.meta
Assets/Sprites/background/jungle_tree1.png
Assets/Sprites/background/jungle_tree1.png.meta
Assets/Sprites/background/jungle_tree1_bg.png
Assets/Sprites/background/jungle_tree1_bg.png.meta
Assets/Sprites/background/jungle_tree2.png
Assets/Sprites/background/jungle_tree2.png.meta
Assets/Sprites/background/jungle_tree2_bg.png
Assets/Sprites/background/jungle_tree2_bg.png.meta
Assets/Sprites/background/tile_cave_blob_1.png
Assets/Sprites/background/tile_cave_blob_1.png.meta
Assets/Sprites/background/tile_cave_hole_1.png
Assets/Sprites/background/tile_cave_hole_1.png.meta
Assets/Sprites/boss.meta
Assets/Sprites/boss/BossBody-static.png
Assets/Sprites/boss/BossBody-static.png.meta
Assets/Sprites/boss/BossBodyIdle.png
Assets/Sprites/boss/BossBodyIdle.png.meta
Assets/Sprites/boss/BossHead-static.png
Assets/Sprites/boss/BossHead-static.png.meta
Assets/Sprites/boss/BossHeadIdle.png
Assets/Sprites/boss/BossHeadIdle.png.meta
Assets/Sprites/boss/BossScreen_Anim_intro.png
Assets/Sprites/boss/BossScreen_Anim_intro.png.meta
Assets/Sprites/boss/BossScreen_Anim_openmouth_fire.png
Assets/Sprites/boss/BossScreen_Anim_openmouth_fire.png.meta
Assets/Sprites/boss/BossScreen_rockBG.png
Assets/Sprites/boss/BossScreen_rockBG.png.meta
Assets/Sprites/boss/BossScreen_rockcache.png
Assets/Sprites/boss/BossScreen_rockcache.png.meta
Assets/Sprites/boss/BossScreen_rockcache2.png
Assets/Sprites/boss/BossScreen_rockcache2.png.meta
Assets/Sprites/boss/BossStatic.png
Assets/Sprites/boss/BossStatic.png.meta
Assets/Sprites/boss/Boss_Fire.png
Assets/Sprites/boss/Boss_Fire.png.meta
Assets/Sprites/boss/Boss_Fire360_spritesheet.png
Assets/Sprites/boss/Boss_Fire360_spritesheet.png.meta
Assets/Sprites/boss/Boss_Fire_Expl.png
Assets/Sprites/boss/Boss_Fire_Expl.png.meta
Assets/Sprites/boss/Boss_laser.png
Assets/Sprites/boss/Boss_laser.png.meta
Assets/Sprites/boss/sParticlesLaser.png
Assets/Sprites/boss/sParticlesLaser.png.meta
Assets/Sprites/boss/sparks.png
Assets/Sprites/boss/sparks.png.meta
Assets/Sprites/cave_tileset.png
Assets/Sprites/cave_tileset.png.meta
Assets/Sprites/enemy.meta
Assets/Sprites/enemy/enemy_weapon_bullet.png
Assets/Sprites/enemy/enemy_weapon_bullet.png.meta
Assets/Sprites/enemy/grunt.png
Assets/Sprites/enemy/grunt.png.meta
Assets/Sprites/enemy/grunt_crouch.png
Assets/Sprites/enemy/grunt_crouch.png.meta
Assets/Sprites/enemy/grunt_crouch_shoot_front.png
Assets/Sprites/enemy/grunt_crouch_shoot_front.png.meta
Assets/Sprites/enemy/grunt_death.png
Assets/Sprites/enemy/grunt_death.png.meta
Assets/Sprites/enemy/grunt_idle.png
Assets/Sprites/enemy/grunt_idle.png.meta
Assets/Sprites/enemy/grunt_portal.png
Assets/Sprites/enemy/grunt_portal.png.meta
Assets/Sprites/enemy/grunt_portal_broke.png
Assets/Sprites/enemy/grunt_portal_broke.png.meta
Assets/Sprites/enemy/grunt_run.png
Assets/Sprites/enemy/grunt_run.png.meta
Assets/Sprites/enemy/grunt_shoot.png
Assets/Sprites/enemy/grunt_shoot.png.meta
Assets/Sprites/enemy/turret.png
Assets/Sprites/enemy/turret.png.meta
Assets/Sprites/enemy/turret_broke.png
Assets/Sprites/enemy/turret_broke.png.meta
Assets/Sprites/fx.meta
Assets/Sprites/fx/bullet_impact.png
Assets/Sprites/fx/bullet_impact.png.meta
Assets/Sprites/fx/explosion_red.png
Assets/Sprites/fx/explosion_red.png.meta
Assets/Sprites/fx/explosion_smoke.png
Assets/Sprites/fx/explosion_smoke.png.meta
Assets/Sprites/fx/particles_dirt.png
Assets/Sprites/fx/particles_dirt.png.meta
Assets/Sprites/fx/particles_explosion.png
Assets/Sprites/fx/particles_explosion.png.meta
Assets/Sprites/fx/particles_grunt.png
Assets/Sprites/fx/particles_grunt.png.meta
Assets/Sprites/fx/particles_palette.png
Assets/Sprites/fx/particles_palette.png.meta
Assets/Sprites/fx/particles_turret.png
Assets/Sprites/fx/particles_turret.png.meta
Assets/Sprites/fx/shadow_char.png
Assets/Sprites/fx/shadow_char.png.meta
Assets/Sprites/player.meta
Assets/Sprites/player/john_crouch.png
Assets/Sprites/player/john_crouch.png.meta
Assets/Sprites/player/john_crouch_ng.png
Assets/Sprites/player/john_crouch_ng.png.meta
Assets/Sprites/player/john_crouch_shoot.png
Assets/Sprites/player/john_crouch_shoot.png.meta
Assets/Sprites/player/john_crouch_shoot_ng.png
Assets/Sprites/player/john_crouch_shoot_ng.png.meta
Assets/Sprites/player/john_dead.png
Assets/Sprites/player/john_dead.png.meta
Assets/Sprites/player/john_dead_soul.png
Assets/Sprites/player/john_dead_soul.png.meta
Assets/Sprites/player/john_defeated.png
Assets/Sprites/player/john_defeated.png.meta
Assets/Sprites/player/john_defeated_ng.png
Assets/Sprites/player/john_defeated_ng.png.meta
Assets/Sprites/player/john_hagging.png
Assets/Sprites/player/john_hagging.png.meta
Assets/Sprites/player/john_hagging_aimdown.png
Assets/Sprites/player/john_hagging_aimdown.png.meta
Assets/Sprites/player/john_hagging_aimdown_firing.png
Assets/Sprites/player/john_hagging_aimdown_firing.png.meta
Assets/Sprites/player/john_hagging_aimdowndiag.png
Assets/Sprites/player/john_hagging_aimdowndiag.png.meta
Assets/Sprites/player/john_hagging_aimdowndiag_firing.png
Assets/Sprites/player/john_hagging_aimdowndiag_firing.png.meta
Assets/Sprites/player/john_hagging_aimupdiag.png
Assets/Sprites/player/john_hagging_aimupdiag.png.meta
Assets/Sprites/player/john_hagging_aimupdiag_firing.png
Assets/Sprites/player/john_hagging_aimupdiag_firing.png.meta
Assets/Sprites/player/john_hagging_aimupup.png
Assets/Sprites/player/john_hagging_aimupup.png.meta
Assets/Sprites/player/john_hagging_aimupup_firing.png
Assets/Sprites/player/john_hagging_aimupup_firing.png.meta
Assets/Sprites/player/john_hagging_fire_right.png
Assets/Sprites/player/john_hagging_fire_right.png.meta
Assets/Sprites/player/john_hagging_idle.png
Assets/Sprites/player/john_hagging_idle.png.meta
Assets/Sprites/player/john_hagging_move.png
Assets/Sprites/player/john_hagging_move.png.meta
Assets/Sprites/player/john_hithurt.png
Assets/Sprites/player/john_hithurt.png.meta
Assets/Sprites/player/john_hithurt_ng.png
Assets/Sprites/player/john_hithurt_ng.png.meta
Assets/Sprites/player/john_idle.png
Assets/Sprites/player/john_idle.png.meta
Assets/Sprites/player/john_idle_ng.png
Assets/Sprites/player/john_idle_ng.png.meta
Assets/Sprites/player/john_jump.png
Assets/Sprites/player/john_jump.png.meta
Assets/Sprites/player/john_jump_ng.png
Assets/Sprites/player/john_jump_ng.png.meta
Assets/Sprites/player/john_jump_ng_aimdiagdown.png
Assets/Sprites/player/john_jump_ng_aimdiagdown.png.meta
Assets/Sprites/player/john_jump_ng_aimdiagup.png
Assets/Sprites/player/john_jump_ng_aimdiagup.png.meta
Assets/Sprites/player/john_jump_ng_aimdown.png
Assets/Sprites/player/john_jump_ng_aimdown.png.meta
Assets/Sprites/player/john_jump_ng_aimup.png
Assets/Sprites/player/john_jump_ng_aimup.png.meta
Assets/Sprites/player/john_landing.png
Assets/Sprites/player/john_landing.png.meta
Assets/Sprites/player/john_run.png
Assets/Sprites/player/john_run.png.meta
Assets/Sprites/player/john_run_NG_diag_aimdowndiag.png
Assets/Sprites/player/john_run_NG_diag_aimdowndiag.png.meta
Assets/Sprites/player/john_run_ng.png
Assets/Sprites/player/john_run_ng.png.meta
Assets/Sprites/player/john_run_shoot.png
Assets/Sprites/player/john_run_shoot.png.meta
Assets/Sprites/player/john_run_shoot_ng.png
Assets/Sprites/player/john_run_shoot_ng.png.meta
Assets/Sprites/player/john_run_shoot_up_diag.png
Assets/Sprites/player/john_run_shoot_up_diag.png.meta
Assets/Sprites/player/john_run_up_diag.png
Assets/Sprites/player/john_run_up_diag.png.meta
Assets/Sprites/player/john_stand_looking_down_diag.png
Assets/Sprites/player/john_stand_looking_down_diag.png.meta
Assets/Sprites/player/john_stand_looking_up.png
Assets/Sprites/player/john_stand_looking_up.png.meta
Assets/Sprites/player/john_stand_looking_up_diag.png
Assets/Sprites/player/john_stand_looking_up_diag.png.meta
Assets/Sprites/player/john_stand_shooting.png
Assets/Sprites/player/john_stand_shooting.png.meta
Assets/Sprites/player/john_stand_shooting_down_diag.png
Assets/Sprites/player/john_stand_shooting_down_diag.png.meta
Assets/Sprites/player/john_stand_shooting_ng.png
Assets/Sprites/player/john_stand_shooting_ng.png.meta
Assets/Sprites/player/john_stand_shooting_up.png
Assets/Sprites/player/john_stand_shooting_up.png.meta
Assets/Sprites/player/john_stand_shooting_up_diag.png
Assets/Sprites/player/john_stand_shooting_up_diag.png.meta
Assets/Sprites/player/john_stand_up_diag.png
Assets/Sprites/player/john_stand_up_diag.png.meta
Assets/Sprites/player/john_static.png
Assets/Sprites/player/john_static.png.meta
Assets/Sprites/player/jump_dust.png
Assets/Sprites/player/jump_dust.png.meta
Assets/Sprites/player/player_weapon_break.png
Assets/Sprites/player/player_weapon_break.png.meta
Assets/Sprites/player/run_dust.png
Assets/Sprites/player/run_dust.png.meta
Assets/Sprites/player/weapon_bullet.png
Assets/Sprites/player/weapon_bullet.png.meta
Assets/Sprites/player/weapon_bullet_level2.png
Assets/Sprites/player/weapon_bullet_level2.png.meta
Assets/Sprites/props.meta
Assets/Sprites/props/ammo.png
Assets/Sprites/props/ammo.png.meta
Assets/Sprites/props/barrel.png
Assets/Sprites/props/barrel.png.meta
Assets/Sprites/props/bigcrate.png
Assets/Sprites/props/bigcrate.png.meta
Assets/Sprites/props/crate.png
Assets/Sprites/props/crate.png.meta
Assets/Sprites/props/plant.png
Assets/Sprites/props/plant.png.meta
Assets/Sprites/props/red_barrel.png
Assets/Sprites/props/red_barrel.png.meta
Assets/Sprites/props/shelter.png
Assets/Sprites/props/shelter.png.meta
Assets/Sprites/props/skullpanel.png
Assets/Sprites/props/skullpanel.png.meta
Assets/Sprites/tiles_spritesheet.png
Assets/Sprites/tiles_spritesheet.png.meta
Assets/Sprites/tileset.png
Assets/Sprites/tileset.png.meta
Assets/Sprites/titlescreen.meta
Assets/Sprites/titlescreen/CreditsScreen.png
Assets/Sprites/titlescreen/CreditsScreen.png.meta
Assets/Sprites/titlescreen/GameOverScreen-still.png
Assets/Sprites/titlescreen/GameOverScreen-still.png.meta
Assets/Sprites/titlescreen/GameOverScreen.png
Assets/Sprites/titlescreen/GameOverScreen.png.meta
Assets/Sprites/titlescreen/main_title_bg.png
Assets/Sprites/titlescreen/main_title_bg.png.meta
Assets/Sprites/titlescreen/main_title_press_start(201x23).png
Assets/Sprites/titlescreen/main_title_press_start(201x23).png.meta
Assets/Sprites/titlescreen/main_title_press_start(201x23)_x.5.png
Assets/Sprites/titlescreen/main_title_press_start(201x23)_x.5.png.meta
Assets/Sprites/titlescreen/main_title_title.png
Assets/Sprites/titlescreen/main_title_title.png.meta
Assets/Sprites/titlescreen/main_title_title_x.5.png
Assets/Sprites/titlescreen/main_title_title_x.5.png.meta
Assets/Sprites/titlescreen/title_screen.png
Assets/Sprites/titlescreen/title_screen.png.meta
Assets/Sprites/ui.meta
Assets/Sprites/ui/fnt_wonder32_custom.png
Assets/Sprites/ui/fnt_wonder32_custom.png.meta
Assets/Sprites/ui/fnt_wonder32_customm.png
Assets/Sprites/ui/fnt_wonder32_customm.png.meta
Assets/Sprites/ui/gun_icon.png
Assets/Sprites/ui/gun_icon.png.meta
Assets/Sprites/ui/life_empty.png
Assets/Sprites/ui/life_empty.png.meta
Assets/Sprites/ui/life_unit.png
Assets/Sprites/ui/life_unit.png.meta
Assets/Sprites/ui/multiplier_icon.png
Assets/Sprites/ui/multiplier_icon.png.meta
Assets/Sprites/ui/multiplier_x1.png
Assets/Sprites/ui/multiplier_x1.png.meta
Assets/Sprites/ui/multiplier_x2.png
Assets/Sprites/ui/multiplier_x2.png.meta
Assets/Sprites/ui/player_icon_idle.png
Assets/Sprites/ui/player_icon_idle.png.meta
Assets/Sprites/ui/ui_medal_life.png
Assets/Sprites/ui/ui_medal_life.png.meta
Assets/Sprites/ui/ui_medal_life_red.png
Assets/Sprites/ui/ui_medal_life_red.png.meta
Assets/Sprites/ui/ui_nade_blue.png
Assets/Sprites/ui/ui_nade_blue.png.meta
Assets/Sprites/ui/ui_nade_red.png
Assets/Sprites/ui/ui_nade_red.png.meta
Assets/Sprites/ui/ui_weapon_curve_blue.png
Assets/Sprites/ui/ui_weapon_curve_blue.png.meta
Assets/Sprites/ui/ui_weapon_double_red.png
Assets/Sprites/ui/ui_weapon_double_red.png.meta
Assets/Sprites/ui/ui_weapon_grenadier_blue.png
Assets/Sprites/ui/ui_weapon_grenadier_blue.png.meta
Assets/Sprites/ui/ui_weapon_missile_red.png
Assets/Sprites/ui/ui_weapon_missile_red.png.meta
Assets/Sprites/ui/ui_weapon_repeater_blue.png
Assets/Sprites/ui/ui_weapon_repeater_blue.png.meta
Assets/Sprites/ui/ui_weapon_shield_red.png
Assets/Sprites/ui/ui_weapon_shield_red.png.meta
Assets/Sprites/ui/ui_weapon_target_red.png
Assets/Sprites/ui/ui_weapon_target_red.png.meta
Assets/Sprites/ui/ui_weapon_tribow_blue.png
Assets/Sprites/ui/ui_weapon_tribow_blue.png.meta
Packages/manifest.json
Packages/packages-lock.json
ProjectSettings/AudioManager.asset
ProjectSettings/ClusterInputManager.asset
ProjectSettings/DynamicsManager.asset
ProjectSettings/EditorBuildSettings.asset
ProjectSettings/EditorSettings.asset
ProjectSettings/GraphicsSettings.asset
ProjectSettings/InputManager.asset
ProjectSettings/MemorySettings.asset
ProjectSettings/NavMeshAreas.asset
ProjectSettings/PackageManagerSettings.asset
ProjectSettings/Packages/com.unity.testtools.codecoverage/Settings.json
ProjectSettings/Physics2DSettings.asset
ProjectSettings/PresetManager.asset
ProjectSettings/ProjectSettings.asset
ProjectSettings/ProjectVersion.txt
ProjectSettings/QualitySettings.asset
ProjectSettings/SceneTemplateSettings.json
ProjectSettings/TagManager.asset
ProjectSettings/TimeManager.asset
ProjectSettings/UnityConnectSettings.asset
ProjectSettings/VFXManager.asset
ProjectSettings/VersionControlSettings.asset
ProjectSettings/XRSettings.asset
